### PR TITLE
 using the r…

### PR DESCRIPTION
**Pull request by arpitgoyalhtmedia**
included the python script imitating upload-local-file.sh using the requests library provided in python.

### CODE REVIEW

**Comment by tleyden** [comment]
Thanks for the contribution!

**Comment by arpitgoyalhtmedia** [comment]
@tleyden  I was wondering why are we still using the image provided by Tutum here? In my application I used the one provided with docker. Also the rabbitmq username and password are exposed in the yml file itself... should we change that?

**Comment by tleyden** [comment]
Yeah I want to change it, it's just because I haven't had a chance to test it.  Have you tried it out?

**Comment by arpitgoyalhtmedia** [comment]
I will make the required changes and create a pull request by today.

**Comment by tleyden** [comment]
Looking forward to it!

**Pull request merged**
